import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const openSans = Open_Sans({
  weight: '400',
  subsets: ['latin'],
  variable: '--openSans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={openSans.variable}>
        <main className="flex min-h-screen flex-col items-center p-8 leading-8 relative">
          <div className="fixed z-20 w-full top-0">
            <Navbar isSignedIn={true} />
          </div>
          <div className="flex flex-col items-center md:w-10/12 lg:w-8/12 xl:w-6/12 z-10">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
